#ifndef GAMESTATE_H
#define GAMESTATE_H

enum GameState {
  STATE_SPLASH,
  STATE_GAME_MENU,
  STATE_SNAKE_SPEED,
  STATE_SNAKE_GAME,
  STATE_SNAKE_SCORE,
  STATE_BREAKOUT_GAME,  
  STATE_DINO_GAME,
  STATE_CHESS_GAME,
  STATE_LOGO_VIEW,
  STATE_CITY_DRIVE_GAME
};

#endif

